### ISSUE TITLE
Missing shared libraries /usr/bin/ld: cannot find -ldmitigr_net

### ISSUE THREAD

**Issue by rostislav-nikitin** [dmitigr/cpplipa#6]
After I built the cefeika (shared libs) as specified there: https://github.com/dmitigr/cefeika#installation-on-linux
Installed them with sudo make install
And then used this instructions: https://github.com/dmitigr/cefeika#usage-with-cmake
It fails to build a very simple test_conn.cpp file:
```
#include <iostream>

int main(void)
{
        std::cout << "Test" << std::endl;
        return 0;
}
```

with a next error:

Scanning dependencies of target test_conn
[ 50%] Building CXX object CMakeFiles/test_conn.dir/test_conn.cpp.o
[100%] Linking CXX executable test_conn
/usr/bin/ld: cannot find -ldmitigr_net
/usr/bin/ld: cannot find -ldmitigr_os
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/test_conn.dir/build.make:105: test_conn] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/test_conn.dir/all] Error 2
make: *** [Makefile:103: all] Error 2

And yep, ldconfig -p returns only below ones (no libdmitigr_net.so or libdmitigr_os.so):

▶ ldconfig -p | grep dmit 
        libdmitigr_wsd.so.0.1 (libc6,x86-64) => /usr/local/lib/libdmitigr_wsd.so.0.1
        libdmitigr_wsd.so (libc6,x86-64) => /usr/local/lib/libdmitigr_wsd.so
        libdmitigr_wscld.so.0.1 (libc6,x86-64) => /usr/local/lib/libdmitigr_wscld.so.0.1
        libdmitigr_wscld.so (libc6,x86-64) => /usr/local/lib/libdmitigr_wscld.so
        libdmitigr_pgfed.so.1.0 (libc6,x86-64) => /usr/local/lib/libdmitigr_pgfed.so.1.0
        libdmitigr_pgfed.so (libc6,x86-64) => /usr/local/lib/libdmitigr_pgfed.so
        libdmitigr_fcgid.so.1.0 (libc6,x86-64) => /usr/local/lib/libdmitigr_fcgid.so.1.0
        libdmitigr_fcgid.so (libc6,x86-64) => /usr/local/lib/libdmitigr_fcgid.so

▶ uname -a               
Linux localhost.localdomain 5.11.18-200.fc33.x86_64 #1 SMP Mon May 3 15:05:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dmitigr** [comment]
Hi Rostislav!

Sorry, I just noticed your issue! (I don't understand why I don't get notified by Github?)

Is this issue actual with the latest commits?
